### ISSUE TITLE
Deprecated selector in `mark\styles\mark.less`

### ISSUE THREAD

**Issue by s0ra** [olmokramer/atom-mark#8]
In `mark\styles\mark.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter .line-number.marked .icon-right` => `atom-text-editor.editor .gutter .line-number.marked .icon-right`

* `atom-text-editor::shadow .gutter .line-number.marked .icon-right:before` => `atom-text-editor.editor .gutter .line-number.marked .icon-right:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by sagearbor** [comment]
I still received above error when I installed mark package in atom on Jan 29th 2020 on a pc.  The command "Ctrl-k, Ctrl-k" does not mark the line.
